name: tenant_manager
description: A Flutter tenant management app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  # Utilities
  uuid: ^4.5.3
  intl: ^0.20.3

  # Charts
  fl_chart: ^1.1.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

  # Images
  image_picker: 1.0.7
  file_picker: 8.1.7

  # PDF & Printing
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.3

  # Networking
  http: ^1.2.2

  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: 10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true