// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6BzBaQmU_oh9Y7bwLZdUOPiIoDnWsmQ',
    appId: '1:922083526775:web:7b2a6cb7eb4f3aee5fde72',
    messagingSenderId: '922083526775',
    projectId: 'tenant-manager-f4ac6',
    authDomain: 'tenant-manager-f4ac6.firebaseapp.com',
    storageBucket: 'tenant-manager-f4ac6.firebasestorage.app',
    measurementId: 'G-K0L1CYVHXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABlTZhDf7u49GkzUmhGRKnLnJMlu6ubzs',
    appId: '1:922083526775:android:8581c939d8c004785fde72',
    messagingSenderId: '922083526775',
    projectId: 'tenant-manager-f4ac6',
    storageBucket: 'tenant-manager-f4ac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoJPv5Md_AFA3nQylLMBnCeSltKVn0Lk8',
    appId: '1:922083526775:ios:85fd8a777344b68b5fde72',
    messagingSenderId: '922083526775',
    projectId: 'tenant-manager-f4ac6',
    storageBucket: 'tenant-manager-f4ac6.firebasestorage.app',
    iosBundleId: 'com.example.tenantManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoJPv5Md_AFA3nQylLMBnCeSltKVn0Lk8',
    appId: '1:922083526775:ios:85fd8a777344b68b5fde72',
    messagingSenderId: '922083526775',
    projectId: 'tenant-manager-f4ac6',
    storageBucket: 'tenant-manager-f4ac6.firebasestorage.app',
    iosBundleId: 'com.example.tenantManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6BzBaQmU_oh9Y7bwLZdUOPiIoDnWsmQ',
    appId: '1:922083526775:web:829b8a76d207f90c5fde72',
    messagingSenderId: '922083526775',
    projectId: 'tenant-manager-f4ac6',
    authDomain: 'tenant-manager-f4ac6.firebaseapp.com',
    storageBucket: 'tenant-manager-f4ac6.firebasestorage.app',
    measurementId: 'G-4DRSH1JGZM',
  );
}
